GRANT USAGE ON SCHEMA finance TO erp_app;
GRANT ALL ON ALL TABLES IN SCHEMA finance TO erp_app;
GRANT ALL ON ALL SEQUENCES IN SCHEMA finance TO erp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT ALL ON TABLES TO erp_app;
