namespace ERPSystem.Core.Actions
{
    public static class EntityActionRegistry
    {
        private static readonly Dictionary<EntityType, IReadOnlyList<EntityActionDefinition>> _actions = new()
        {
            [EntityType.Customer] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.CustomerStatement, "كشف حساب", "\uE8A1", "الحسابات"),
                new(EntityActionId.CustomerReceivables, "الذمم", "\uE8C1", "الحسابات"),
                new(EntityActionId.CustomerReceipt, "سند قبض", "\uE7BF", "السندات"),
                new(EntityActionId.CustomerPayment, "سند دفع", "\uE719", "السندات"),
                new(EntityActionId.CustomerInvoices, "فواتير العميل", "\uE9F9", "المستندات"),
                new(EntityActionId.CustomerSalesDetails, "تفاصيل بيع", "\uE8F1", "المستندات"),
                new(EntityActionId.CustomerDetails, "تفاصيل العميل", "\uE716", "العميل"),
                new(EntityActionId.CustomerEdit, "تعديل العميل", "\uE70F", "العميل"),
                new(EntityActionId.CustomerDeactivate, "تعطيل العميل", "\uE7E8", "العميل", destructive: true),
            ],
            [EntityType.SalesInvoice] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.InvoiceView, "عرض التفاصيل", "\uE7B3"),
                new(EntityActionId.InvoiceEdit, "تعديل الفاتورة", "\uE70F", "التحرير"),
                new(EntityActionId.InvoiceSendToWarehouse, "إرسال للمستودع", "\uE72A", "سير العمل"),
                new(EntityActionId.InvoiceDetailLengths, "تفصيل الأطوال", "\uE8CB", "سير العمل"),
                new(EntityActionId.InvoiceApprove, "اعتماد", "\uE73E", "سير العمل"),
                new(EntityActionId.InvoiceApproveAndDeliver, "اعتماد وتسليم", "\uE7C1", "سير العمل"),
                new(EntityActionId.InvoiceDeliver, "تسليم", "\uE7C1", "سير العمل"),
                new(EntityActionId.InvoicePrint, "طباعة", "\uE749", "طباعة"),
                new(EntityActionId.InvoiceExportPdf, "تصدير PDF", "\uEDE1", "طباعة"),
                new(EntityActionId.InvoiceReturn, "إنشاء مرتجع", "\uE7A6", "المرتجعات"),
                new(EntityActionId.InvoiceViewReturns, "عرض المرتجعات", "\uE72C", "المرتجعات"),
                new(EntityActionId.InvoiceCallCustomer, "اتصل بالعميل", "\uE717", "العميل"),
                new(EntityActionId.InvoiceCancel, "إلغاء الفاتورة", "\uE711", "خطر", destructive: true),
            ],
            [EntityType.FabricItem] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.FabricCard, "بطاقة الصنف", "\uE8A5"),
                new(EntityActionId.FabricMovement, "حركة الصنف", "\uE8CB"),
                new(EntityActionId.FabricEdit, "تعديل الصنف", "\uE70F"),
                new(EntityActionId.FabricPriceEdit, "تعديل السعر", "\uE8C1"),
                new(EntityActionId.FabricTransfer, "مناقلة", "\uE8AB"),
                new(EntityActionId.FabricDeactivate, "تعطيل الصنف", "\uE7E8", destructive: true),
            ],
            [EntityType.Supplier] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.SupplierStatement, "كشف حساب المورد", "\uE8A1"),
                new(EntityActionId.SupplierPayment, "سند دفع", "\uE719"),
                new(EntityActionId.SupplierInvoices, "فواتير المورد", "\uE9F9"),
                new(EntityActionId.SupplierDetails, "تفاصيل المورد", "\uE779"),
                new(EntityActionId.SupplierEdit, "تعديل المورد", "\uE70F"),
                new(EntityActionId.SupplierDeactivate, "تعطيل المورد", "\uE7E8", destructive: true),
            ],
            [EntityType.PurchaseInvoice] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.PurchaseView, "عرض التفاصيل", "\uE7B3"),
                new(EntityActionId.PurchasePrint, "طباعة", "\uE749"),
                new(EntityActionId.PurchaseExportPdf, "تصدير PDF", "\uEDE1"),
                new(EntityActionId.PurchaseReturn, "إنشاء مرتجع", "\uE7A6"),
                new(EntityActionId.PurchaseCancel, "إلغاء", "\uE711", destructive: true),
            ],
            [EntityType.ImportContainer] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.ContainerDetails, "تفاصيل الحاوية", "\uE7B3"),
                new(EntityActionId.ContainerImportReview, "مراجعة الاستيراد", "\uE8B7"),
                new(EntityActionId.ContainerDistribution, "توزيع الكميات على العملاء", "\uE8AB"),
                new(EntityActionId.ContainerStocktake, "جرد الحاوية", "\uE7B3"),
                new(EntityActionId.ContainerCosts, "تكلفة الاستيراد", "\uE8C1"),
                new(EntityActionId.ContainerDocumentation, "استيراد ملفات توثيق", "\uE8B7", "المستندات"),
                new(EntityActionId.ContainerApprove, "اعتماد الحاوية", "\uE73E"),
                new(EntityActionId.ContainerArchive, "أرشفة الحاوية", "\uE7B8", destructive: true),
                new(EntityActionId.ContainerDelete, "حذف", "\uE74D", destructive: true),
            ],
            [EntityType.Employee] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.EmployeeProfile, "ملف الموظف", "\uE716"),
                new(EntityActionId.EmployeeAttendance, "سجل الدوام", "\uE823"),
                new(EntityActionId.EmployeeLeaves, "الإجازات", "\uE787"),
                new(EntityActionId.EmployeeContracts, "العقود", "\uE8A5"),
                new(EntityActionId.EmployeeEdit, "تعديل الموظف", "\uE70F"),
                new(EntityActionId.EmployeeDeactivate, "تعطيل الموظف", "\uE7E8", destructive: true),
            ],
            [EntityType.Warehouse] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.WarehouseEdit, "تعديل", "\uE70F", "المستودع"),
                new(EntityActionId.FabricTransfer, "مناقلة", "\uE8AB", "المخزون"),
                new(EntityActionId.WarehouseStockReport, "تقرير المخزون", "\uE9D2", "التقارير"),
                new(EntityActionId.FabricMovement, "حركات المستودع", "\uE8CB", "المخزون"),
                new(EntityActionId.WarehouseStocktake, "جرد", "\uE7B3", "المخزون"),
                new(EntityActionId.WarehouseTimeline, "الخط الزمني", "\uE823", "التدقيق"),
                new(EntityActionId.WarehouseAudit, "التدقيق", "\uE7C3", "التدقيق"),
                new(EntityActionId.WarehouseExportExcel, "تصدير Excel", "\uEDE1", "التصدير"),
                new(EntityActionId.WarehouseExportPdf, "تصدير PDF", "\uEDE1", "التصدير"),
                new(EntityActionId.WarehousePrint, "طباعة", "\uE749", "التصدير"),
                new(EntityActionId.WarehouseDuplicate, "نسخ", "\uE8C8", "المستودع"),
                new(EntityActionId.WarehouseProperties, "خصائص", "\uE946", "المستودع"),
                new(EntityActionId.WarehouseArchive, "أرشفة", "\uE7B8", "المستودع", destructive: true),
                new(EntityActionId.WarehouseActivate, "تفعيل", "\uE73E", "المستودع"),
            ],
            [EntityType.Cashbox] =
            [
                new(EntityActionId.OpenOperationsCenter, "فتح مركز العمليات", "\uE8A7"),
                new(EntityActionId.CashboxEdit, "تعديل الصندوق", "\uE70F", "الصندوق"),
                new(EntityActionId.CashboxTransfer, "تحويل بين الصناديق", "\uE8AB", "التحويلات"),
                new(EntityActionId.CashboxMovements, "حركات الصندوق", "\uE8CB", "الحركة"),
                new(EntityActionId.CustomerReceipt, "سند قبض", "\uE7BF", "السندات"),
                new(EntityActionId.CustomerPayment, "سند دفع", "\uE719", "السندات"),
                new(EntityActionId.CashboxProperties, "خصائص", "\uE946", "الصندوق"),
                new(EntityActionId.CashboxDeactivate, "تعطيل", "\uE7E8", "الصندوق", destructive: true),
                new(EntityActionId.CashboxActivate, "تفعيل", "\uE73E", "الصندوق"),
            ],
            [EntityType.JournalEntry] =
            [
                new(EntityActionId.JournalDetails, "عرض القيد", "\uE7B3"),
                new(EntityActionId.JournalApprove, "اعتماد", "\uE73E", "سير العمل"),
                new(EntityActionId.JournalPost, "ترحيل", "\uE8C1", "سير العمل"),
                new(EntityActionId.JournalReverse, "عكس القيد", "\uE7A6", "سير العمل", destructive: true),
                new(EntityActionId.VoucherPrint, "طباعة السند", "\uE749"),
                new(EntityActionId.VoucherExportPdf, "تصدير PDF", "\uEDE1"),
                new(EntityActionId.JournalCancel, "إلغاء القيد", "\uE711", destructive: true),
            ],
            [EntityType.Account] =
            [
                new(EntityActionId.AccountDetails, "عرض التفاصيل", "\uE7B3"),
                new(EntityActionId.AccountLedger, "كشف حساب", "\uE8A1", "التقارير"),
                new(EntityActionId.AccountEdit, "تعديل الحساب", "\uE70F", "الحساب"),
                new(EntityActionId.AccountAddChild, "حساب فرعي", "\uE710", "الحساب"),
                new(EntityActionId.AccountDeactivate, "تعطيل الحساب", "\uE7E8", "الحساب", destructive: true),
            ],
            [EntityType.Expense] =
            [
                new(EntityActionId.ExpenseOperationsCenter, "مركز العمليات", "\uE8A7"),
                new(EntityActionId.ExpenseDetails, "عرض التفاصيل", "\uE7B3"),
                new(EntityActionId.ExpenseEdit, "تعديل", "\uE70F", "المصروف"),
                new(EntityActionId.ExpenseApprove, "اعتماد", "\uE73E", "سير العمل"),
                new(EntityActionId.ExpenseReject, "رفض", "\uE711", "سير العمل", destructive: true),
                new(EntityActionId.ExpenseSchedulePayment, "جدولة دفعة", "\uE787", "المالية"),
                new(EntityActionId.ExpenseRecordPayment, "تسجيل دفعة", "\uE719", "المالية"),
                new(EntityActionId.ExpenseDuplicate, "نسخ", "\uE8C8", "المصروف"),
                new(EntityActionId.ExpensePaymentHistory, "سجل الدفعات", "\uE719", "المالية"),
                new(EntityActionId.ExpenseAttachments, "المرفقات", "\uE8B7", "المستندات"),
                new(EntityActionId.ExpenseAuditHistory, "سجل التدقيق", "\uE7C3", "التدقيق"),
                new(EntityActionId.ExpenseTimeline, "الخط الزمني", "\uE823", "التدقيق"),
                new(EntityActionId.ExpenseExportPdf, "تصدير PDF", "\uEDE1", "التصدير"),
                new(EntityActionId.ExpenseExportExcel, "تصدير Excel", "\uEDE1", "التصدير"),
                new(EntityActionId.ExpensePrint, "طباعة", "\uE749", "التصدير"),
                new(EntityActionId.ExpenseShareReport, "مشاركة التقرير", "\uE72D", "التصدير"),
                new(EntityActionId.ExpenseCancel, "إلغاء", "\uE711", "سير العمل", destructive: true),
                new(EntityActionId.ExpenseArchive, "أرشفة", "\uE7B8", "المصروف", destructive: true),
                new(EntityActionId.ExpenseDelete, "حذف", "\uE74D", "المصروف", destructive: true, requiresConfirmation: true),
            ],
            [EntityType.CapitalPartner] =
            [
                new(EntityActionId.CapitalPartnerOperationsCenter, "مركز العمليات", "\uE8A7"),
                new(EntityActionId.CapitalPartnerDetails, "عرض التفاصيل", "\uE7B3"),
                new(EntityActionId.CapitalPartnerEdit, "تعديل", "\uE70F", "الشريك"),
                new(EntityActionId.CapitalPartnerNewInvestment, "استثمار جديد", "\uE710", "المالية"),
                new(EntityActionId.CapitalPartnerWithdrawal, "سحب رأس مال", "\uE719", "المالية"),
                new(EntityActionId.CapitalPartnerProfitDistribution, "توزيع أرباح", "\uE8C1", "المالية"),
                new(EntityActionId.CapitalPartnerLedger, "دفتر الاستثمار", "\uE8A1", "المالية"),
                new(EntityActionId.CapitalPartnerAuditHistory, "سجل التدقيق", "\uE7C3", "التدقيق"),
                new(EntityActionId.CapitalPartnerTimeline, "الخط الزمني", "\uE823", "التدقيق"),
                new(EntityActionId.CapitalPartnerExportPdf, "تصدير PDF", "\uEDE1", "التصدير"),
                new(EntityActionId.CapitalPartnerExportExcel, "تصدير Excel", "\uEDE1", "التصدير"),
                new(EntityActionId.CapitalPartnerPrint, "طباعة", "\uE749", "التصدير"),
                new(EntityActionId.CapitalPartnerArchive, "أرشفة", "\uE7B8", "الشريك", destructive: true),
            ],
        };

        public static IReadOnlyList<EntityActionDefinition> GetActions(EntityType entityType) =>
            _actions.TryGetValue(entityType, out var list) ? list : Array.Empty<EntityActionDefinition>();

        public static string GetActionTitle(EntityActionId actionId, string entityName)
        {
            var baseTitle = actionId switch
            {
                EntityActionId.OpenOperationsCenter => "مركز العمليات",
                EntityActionId.CustomerStatement => "كشف حساب العميل",
                EntityActionId.CustomerReceivables => "ذمم العميل",
                EntityActionId.CustomerReceipt => "سند قبض",
                EntityActionId.CustomerPayment => "سند دفع",
                EntityActionId.CustomerInvoices => "فواتير العميل",
                EntityActionId.CustomerSalesDetails => "تفاصيل بيع العميل",
                EntityActionId.CustomerDetails => "مركز عمليات العميل",
                EntityActionId.CustomerEdit => "تعديل العميل",
                EntityActionId.CustomerDeactivate => "تعطيل العميل",
                EntityActionId.InvoiceView => "مركز عمليات فاتورة البيع",
                EntityActionId.InvoiceEdit => "تعديل فاتورة بيع",
                EntityActionId.InvoiceDetailLengths => "تفصيل الأطوال",
                EntityActionId.InvoicePrint => "طباعة فاتورة",
                EntityActionId.InvoiceExportPdf => "تصدير فاتورة PDF",
                EntityActionId.InvoiceReturn => "مرتجع بيع",
                EntityActionId.InvoiceCancel => "إلغاء فاتورة",
                EntityActionId.FabricCard => "مركز عمليات الصنف",
                EntityActionId.FabricMovement => "حركة صنف",
                EntityActionId.FabricEdit => "تعديل صنف",
                EntityActionId.FabricPriceEdit => "تعديل سعر الصنف",
                EntityActionId.FabricTransfer => "مناقلة صنف",
                EntityActionId.FabricDeactivate => "تعطيل صنف",
                EntityActionId.WarehouseEdit => "تعديل المستودع",
                EntityActionId.WarehouseArchive => "أرشفة المستودع",
                EntityActionId.WarehouseActivate => "تفعيل المستودع",
                EntityActionId.WarehouseDuplicate => "نسخ المستودع",
                EntityActionId.WarehouseStockReport => "تقرير مخزون المستودع",
                EntityActionId.WarehouseMovementHistory => "حركات المستودع",
                EntityActionId.WarehouseStocktake => "جرد المستودع",
                EntityActionId.WarehouseTimeline => "الخط الزمني",
                EntityActionId.WarehouseAudit => "تدقيق المستودع",
                EntityActionId.WarehouseExportExcel => "تصدير Excel",
                EntityActionId.WarehouseExportPdf => "تصدير PDF",
                EntityActionId.WarehousePrint => "طباعة",
                EntityActionId.WarehouseProperties => "خصائص المستودع",
                EntityActionId.SupplierStatement => "كشف حساب المورد",
                EntityActionId.SupplierPayment => "سند دفع",
                EntityActionId.SupplierInvoices => "فواتير المورد",
                EntityActionId.SupplierDetails => "مركز عمليات المورد",
                EntityActionId.SupplierEdit => "تعديل المورد",
                EntityActionId.SupplierDeactivate => "تعطيل المورد",
                EntityActionId.PurchaseView => "مركز عمليات فاتورة الشراء",
                EntityActionId.PurchasePrint => "طباعة فاتورة شراء",
                EntityActionId.PurchaseExportPdf => "تصدير فاتورة شراء PDF",
                EntityActionId.PurchaseReturn => "مرتجع شراء",
                EntityActionId.PurchaseCancel => "إلغاء فاتورة شراء",
                EntityActionId.ContainerDetails => "مركز عمليات الحاوية",
                EntityActionId.ContainerImportReview => "مراجعة الاستيراد",
                EntityActionId.ContainerDistribution => "توزيع الكميات",
                EntityActionId.ContainerStocktake => "جرد الحاوية",
                EntityActionId.ContainerApprove => "اعتماد الحاوية",
                EntityActionId.ContainerArchive => "أرشفة الحاوية",
                EntityActionId.ContainerDelete => "حذف الحاوية",
                EntityActionId.ContainerItems => "أصناف الحاوية",
                EntityActionId.ContainerCosts => "تكاليف الاستيراد",
                EntityActionId.ContainerExcelImport => "استيراد Excel",
                EntityActionId.ContainerDocumentation => "توثيق الحاوية",
                EntityActionId.EmployeeProfile => "مركز عمليات الموظف",
                EntityActionId.EmployeeAttendance => "سجل الدوام",
                EntityActionId.EmployeeLeaves => "إجازات الموظف",
                EntityActionId.EmployeeContracts => "عقود الموظف",
                EntityActionId.EmployeeEdit => "تعديل الموظف",
                EntityActionId.EmployeeDeactivate => "تعطيل الموظف",
                EntityActionId.JournalView => "مركز عمليات القيد",
                EntityActionId.VoucherPrint => "طباعة السند",
                EntityActionId.VoucherExportPdf => "تصدير السند PDF",
                EntityActionId.JournalCancel => "إلغاء القيد",
                EntityActionId.ExpenseDetails => "مركز عمل المصروف",
                EntityActionId.ExpenseEdit => "تعديل المصروف",
                EntityActionId.ExpenseDuplicate => "نسخ المصروف",
                EntityActionId.ExpenseArchive => "أرشفة المصروف",
                EntityActionId.ExpenseDelete => "حذف المصروف",
                EntityActionId.ExpensePaymentHistory => "سجل دفعات المصروف",
                EntityActionId.ExpenseAttachments => "مرفقات المصروف",
                EntityActionId.ExpenseAuditHistory => "سجل تدقيق المصروف",
                EntityActionId.ExpenseExportPdf => "تصدير PDF",
                EntityActionId.ExpenseExportExcel => "تصدير Excel",
                EntityActionId.ExpensePrint => "طباعة المصروف",
                EntityActionId.ExpenseShareReport => "مشاركة تقرير المصروف",
                EntityActionId.AccountLedger => "كشف حساب",
                _ => "مساحة عمل"
            };
            return string.IsNullOrWhiteSpace(entityName) ? baseTitle : $"{baseTitle} — {entityName}";
        }
    }
}
