namespace ERPSystem.Core.Actions
{
    public enum EntityActionId
    {
        OpenOperationsCenter,

        CustomerStatement,
        CustomerReceivables,
        CustomerReceipt,
        CustomerPayment,
        CustomerInvoices,
        CustomerDetails,
        CustomerEdit,
        CustomerDeactivate,

        InvoiceView,
        InvoiceEdit,
        InvoiceDetailLengths,
        InvoicePrint,
        InvoiceExportPdf,
        InvoiceReturn,
        InvoiceCancel,

        FabricCard,
        FabricMovement,
        FabricEdit,
        FabricPriceEdit,
        FabricTransfer,
        FabricDeactivate,

        SupplierStatement,
        SupplierPayment,
        SupplierInvoices,
        SupplierDetails,
        SupplierEdit,
        SupplierDeactivate,

        PurchaseView,
        PurchasePrint,
        PurchaseExportPdf,
        PurchaseReturn,
        PurchaseCancel,

        ContainerDetails,
        ContainerImportReview,
        ContainerDistribution,
        ContainerStocktake,
        ContainerApprove,
        ContainerArchive,
        ContainerDelete,
        ContainerItems,
        ContainerCosts,
        ContainerExcelImport,

        EmployeeProfile,
        EmployeeAttendance,
        EmployeeLeaves,
        EmployeeContracts,
        EmployeeEdit,
        EmployeeDeactivate,

        JournalView,
        JournalDetails,
        JournalApprove,
        JournalPost,
        JournalReverse,
        JournalCreate,
        VoucherPrint,
        VoucherExportPdf,
        JournalCancel,

        ExpenseDetails,
        ExpenseEdit,
        ExpenseDuplicate,
        ExpenseArchive,
        ExpenseDelete,
        ExpensePaymentHistory,
        ExpenseAttachments,
        ExpenseAuditHistory,
        ExpenseApprove,
        ExpenseReject,
        ExpenseSchedulePayment,
        ExpenseRecordPayment,
        ExpenseCancel,
        ExpenseTimeline,
        ExpenseOperationsCenter,
        ExpenseExportPdf,
        ExpenseExportExcel,
        ExpensePrint,
        ExpenseShareReport,

        CapitalPartnerDetails,
        CapitalPartnerEdit,
        CapitalPartnerNewInvestment,
        CapitalPartnerWithdrawal,
        CapitalPartnerProfitDistribution,
        CapitalPartnerLedger,
        CapitalPartnerAuditHistory,
        CapitalPartnerTimeline,
        CapitalPartnerOperationsCenter,
        CapitalPartnerArchive,
        CapitalPartnerExportPdf,
        CapitalPartnerExportExcel,
        CapitalPartnerPrint,

        AccountDetails,
        AccountEdit,
        AccountAddChild,
        AccountDeactivate,
        AccountCreate,
        AccountLedger,

        WarehouseEdit,
        WarehouseArchive,
        WarehouseActivate,
        WarehouseDuplicate,
        WarehouseStockReport,
        WarehouseMovementHistory,
        WarehouseStocktake,
        WarehouseTimeline,
        WarehouseAudit,
        WarehouseExportExcel,
        WarehouseExportPdf,
        WarehousePrint,
        WarehouseProperties
    }
}
